export const featuredportfolio =[
    {
        id:1,
        title:"featured1",
        img:"https://www.spec-india.com/wp-content/uploads/2020/01/Top-Companies-Using-ReactJS.png"
    },
    {
        id:2,
        title:"fetured2",
        img:"https://www.spec-india.com/wp-content/uploads/2020/01/Top-Companies-Using-ReactJS.png"
    },
    {
        id:3,
        title:"fetured3",
        img:"https://www.spec-india.com/wp-content/uploads/2020/01/Top-Companies-Using-ReactJS.png"
    },
    {
        id:4,
        title:"fetured4",
        img:"https://www.spec-india.com/wp-content/uploads/2020/01/Top-Companies-Using-ReactJS.png"
    },
    {
        id:5,
        title:"fetured5",
        img:"https://www.spec-india.com/wp-content/uploads/2020/01/Top-Companies-Using-ReactJS.png"
    },
    {
        id:6,
        title:"fetured6",
        img:"https://www.spec-india.com/wp-content/uploads/2020/01/Top-Companies-Using-ReactJS.png"
    },
]

export const webportfolio =[
    {
        id:1,
        title:"featured1",
        img:"https://www.spec-india.com/wp-content/uploads/2020/01/Top-Companies-Using-ReactJS.png"
    },
    {
        id:2,
        title:"fetured2",
        img:"https://www.spec-india.com/wp-content/uploads/2020/01/Top-Companies-Using-ReactJS.png"
    },
    {
        id:3,
        title:"fetured3",
        img:"https://www.spec-india.com/wp-content/uploads/2020/01/Top-Companies-Using-ReactJS.png"
    },
    {
        id:4,
        title:"fetured4",
        img:"https://www.spec-india.com/wp-content/uploads/2020/01/Top-Companies-Using-ReactJS.png"
    },
    {
        id:5,
        title:"fetured5",
        img:"https://www.spec-india.com/wp-content/uploads/2020/01/Top-Companies-Using-ReactJS.png"
    },
    {
        id:6,
        title:"fetured6",
        img:"https://www.spec-india.com/wp-content/uploads/2020/01/Top-Companies-Using-ReactJS.png"
    },

]

export const mobileportfolio =[
    {
        id:1,
        title:"featured1",
        img:"https://www.spec-india.com/wp-content/uploads/2020/01/Top-Companies-Using-ReactJS.png"
    },
    {
        id:2,
        title:"fetured2",
        img:"https://www.spec-india.com/wp-content/uploads/2020/01/Top-Companies-Using-ReactJS.png"
    },
    {
        id:3,
        title:"fetured3",
        img:"https://www.spec-india.com/wp-content/uploads/2020/01/Top-Companies-Using-ReactJS.png"
    },
    {
        id:4,
        title:"fetured4",
        img:"https://www.spec-india.com/wp-content/uploads/2020/01/Top-Companies-Using-ReactJS.png"
    },
    {
        id:5,
        title:"fetured5",
        img:"https://www.spec-india.com/wp-content/uploads/2020/01/Top-Companies-Using-ReactJS.png"
    },
    {
        id:6,
        title:"fetured6",
        img:"https://www.spec-india.com/wp-content/uploads/2020/01/Top-Companies-Using-ReactJS.png"
    },

]

export const contactportfolio =[
    {
        id:1,
        title:"featured1",
        img:"https://www.spec-india.com/wp-content/uploads/2020/01/Top-Companies-Using-ReactJS.png"
    },
    {
        id:2,
        title:"fetured2",
        img:"https://www.spec-india.com/wp-content/uploads/2020/01/Top-Companies-Using-ReactJS.png"
    },
    {
        id:3,
        title:"fetured3",
        img:"https://www.spec-india.com/wp-content/uploads/2020/01/Top-Companies-Using-ReactJS.png"
    },
    {
        id:4,
        title:"fetured4",
        img:"https://www.spec-india.com/wp-content/uploads/2020/01/Top-Companies-Using-ReactJS.png"
    },
    {
        id:5,
        title:"fetured5",
        img:"https://www.spec-india.com/wp-content/uploads/2020/01/Top-Companies-Using-ReactJS.png"
    },
    {
        id:6,
        title:"fetured6",
        img:"https://www.spec-india.com/wp-content/uploads/2020/01/Top-Companies-Using-ReactJS.png"
    },

]

export const designportfolio =[
    {
        id:1,
        title:"featured1",
        img:"https://www.spec-india.com/wp-content/uploads/2020/01/Top-Companies-Using-ReactJS.png"
    },
    {
        id:2,
        title:"fetured2",
        img:"https://www.spec-india.com/wp-content/uploads/2020/01/Top-Companies-Using-ReactJS.png"
    },
    {
        id:3,
        title:"fetured3",
        img:"https://www.spec-india.com/wp-content/uploads/2020/01/Top-Companies-Using-ReactJS.png"
    },
    {
        id:4,
        title:"fetured4",
        img:"https://www.spec-india.com/wp-content/uploads/2020/01/Top-Companies-Using-ReactJS.png"
    },
    {
        id:5,
        title:"fetured5",
        img:"https://www.spec-india.com/wp-content/uploads/2020/01/Top-Companies-Using-ReactJS.png"
    },
    {
        id:6,
        title:"fetured6",
        img:"https://www.spec-india.com/wp-content/uploads/2020/01/Top-Companies-Using-ReactJS.png"
    },

]

